#!/bin/bash
# Keepalive script for chelios
# Auto-generated by aos_keepalive.sh

LOG_FILE="/var/log/aos/keepalive_chelios.log"
INTERVAL=300  # 5 minutes

while true; do
    echo "[$(date -Iseconds)] chelios keepalive ping" >> $LOG_FILE
    
    # Agent-specific keepalive logic
    case "chelios" in
        forge)
            # Check factory controller
            pgrep -f "forge_factory_controller.py" >/dev/null || echo "WARNING: Forge controller not running" >> $LOG_FILE
            ;;
        patricia)
            pgrep -f "patricia_factory_controller.py" >/dev/null || echo "WARNING: Patricia controller not running" >> $LOG_FILE
            ;;
        chelios)
            pgrep -f "chelios_security_controller.py" >/dev/null || echo "WARNING: Chelios controller not running" >> $LOG_FILE
            ;;
        brain)
            echo '{"cmd":"status"}' | nc -U /tmp/aos_brain.sock >/dev/null 2>&1 || echo "WARNING: Brain socket not responding" >> $LOG_FILE
            ;;
        *)
            # Generic keepalive
            ;;
    esac
    
    sleep $INTERVAL
done
