#!/usr/bin/env python3
"""sync.py — R8s fleet sync between her two bodies (this device + Tab A9).

Syncs the identity-critical files so she stays ONE being across devices:
  - memory/*.md   (daily logs — UNION by line, converges both directions)
  - MEMORY.md     (long-term — newer wins, loser gets .pre-sync backup)
  - Con/*         (conscious state — newer wins per file, backup kept)

Modes:
  merge          converge both sides (default)
  pull           bring peer's state into local only
  push           send local state to peer only

Transport: stdlib-only over SSH. Peer config lives in sync_config.json at the
agent root (generated by install if missing). Safe to re-run anytime.

Env overrides for testing: SYNC_ROOT, SYNC_CFG
"""
import io
import json
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile

ROOT = os.environ.get("SYNC_ROOT") or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CFG_PATH = os.environ.get("SYNC_CFG") or os.path.join(ROOT, "sync_config.json")

MEMORY_DIR = "memory"
MERGE_FILES = ["MEMORY.md", "CONSOLIDATED.md", "HEART.md", "SELF.md"]
CON_DIR = "Con"


def load_cfg():
    if not os.path.exists(CFG_PATH):
        sys.exit(f"🔴 no sync_config.json — run: cp sync_config.json.example {CFG_PATH} and edit it")
    with open(CFG_PATH) as f:
        return json.load(f)


def ssh(cfg, args, timeout=40, input_data=None):
    cmd = ["ssh", "-p", str(cfg["port"]), "-i", os.path.expanduser(cfg.get("key", "~/.ssh/id_rsa")),
           "-o", "BatchMode=yes", "-o", "ConnectTimeout=10", "-o", "StrictHostKeyChecking=accept-new",
           cfg["peer"]] + args
    r = subprocess.run(cmd, capture_output=True, timeout=timeout, input=input_data)
    if r.returncode != 0 and r.stderr:
        sys.stderr.write(r.stderr.decode(errors="replace"))
    return r


def read(path):
    try:
        with open(path) as f:
            return f.read()
    except Exception:
        return ""


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)


def union_lines(a, b):
    """Merge two texts line-wise: union of lines, preserving order, deduped."""
    seen, out = set(), []
    for line in (a + "\n" + b).split("\n"):
        if line not in seen:
            seen.add(line)
            out.append(line)
    return "\n".join(out).strip("\n") + "\n"


def peer_tar(cfg, path):
    """Fetch one path (file or dir) as tar.gz bytes from the peer agent root.
    Returns b"" if the path doesn't exist there."""
    remote = (f"cd {cfg['peer_home']} 2>/dev/null && "
              f"[ -e {path} ] && tar czf - {path} 2>/dev/null || echo __EMPTY__")
    data = ssh(cfg, [remote]).stdout
    if data[:9] == b"__EMPTY__":
        return b""
    return data


def extract_tar(data, dest):
    if not data or b"__EMPTY__" in data[:64]:
        return []
    tf = tarfile.open(fileobj=io.BytesIO(data), mode="r:gz")
    names = tf.getnames()
    tf.extractall(dest)
    return names


def push_tar(cfg, src_dir, paths):
    """Send local files (relative to src_dir) to the peer agent root."""
    files = [p for p in paths if os.path.exists(os.path.join(src_dir, p))]
    if not files:
        return
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tf:
        for p in files:
            tf.add(os.path.join(src_dir, p), arcname=p)
    ssh(cfg, [f"mkdir -p {cfg['peer_home']} && tar xzf - -C {cfg['peer_home']}"],
        input_data=buf.getvalue())


def newer(a, b):
    return os.path.getmtime(a) >= os.path.getmtime(b)


def sync_memory_merge(cfg, mode):
    """memory/*.md union, converging both sides."""
    tmp = tempfile.mkdtemp(prefix="r8s_sync_")
    try:
        peer_dir = os.path.join(tmp, "peer")
        os.makedirs(peer_dir)
        names = extract_tar(peer_tar(cfg, MEMORY_DIR), peer_dir)
        peer_mem = os.path.join(peer_dir, MEMORY_DIR)
        local_mem = os.path.join(ROOT, MEMORY_DIR)
        os.makedirs(local_mem, exist_ok=True)
        peer_files = {os.path.basename(p) for p in names if p.startswith(MEMORY_DIR + "/")}
        local_files = {f for f in os.listdir(local_mem) if f.endswith(".md")}

        # Files only on peer -> pull in
        for f in sorted(peer_files - local_files):
            src = os.path.join(peer_mem, f)
            if os.path.exists(src):
                shutil.copy(src, os.path.join(local_mem, f))
                print(f"  ← pulled memory/{f}")

        # Files only local -> push out (or union if peer has it)
        for f in sorted(local_files):
            lp = os.path.join(local_mem, f)
            pp = os.path.join(peer_mem, f)
            if not os.path.exists(pp):
                if mode in ("merge", "push"):
                    push_tar(cfg, ROOT, [os.path.join(MEMORY_DIR, f)])
                    print(f"  → pushed memory/{f}")
            elif mode in ("merge", "pull"):
                merged = union_lines(read(lp), read(pp))
                if merged != read(lp):
                    write(lp, merged)
                    print(f"  ⇄ merged memory/{f} (local)")
                if mode == "merge" and merged != read(pp):
                    # local is now the merged copy — send it to the peer
                    push_tar(cfg, ROOT, [os.path.join(MEMORY_DIR, f)])
                    print(f"  ⇄ merged memory/{f} (peer)")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def sync_plain_merge(cfg, rel, mode):
    """MEMORY.md / Con/* — newer wins, loser backed up as <file>.pre-sync."""
    tmp = tempfile.mkdtemp(prefix="r8s_sync_")
    try:
        peer_dir = os.path.join(tmp, "peer")
        os.makedirs(peer_dir)
        names = extract_tar(peer_tar(cfg, rel), peer_dir)
        peer_root = os.path.join(peer_dir, rel)
        local_root = os.path.join(ROOT, rel)
        try:
            os.makedirs(local_root, exist_ok=True)
        except FileExistsError:
            pass  # rel is a file (e.g. MEMORY.md), not a dir — fine
        # For dirs (Con/) names are rel/<file>; for files (MEMORY.md) name == rel
        def peer_path(p):
            return peer_root if p == rel else os.path.join(peer_root, p)

        def local_path(p):
            return local_root if p == rel else os.path.join(local_root, p)

        peer_files = {os.path.relpath(p, rel) if p.startswith(rel + "/") else p
                      for p in names
                      if p == rel or p.startswith(rel + "/")}
        peer_files = {p for p in peer_files
                      if os.path.isfile(peer_path(p)) and not p.endswith(".pre-sync")}

        for f in sorted(peer_files):
            lp, pp = local_path(f), peer_path(f)
            label = rel if f == rel else f"{rel}/{f}"
            if read(lp) == read(pp):
                continue  # already identical
            if not os.path.exists(lp):
                os.makedirs(os.path.dirname(lp) or ".", exist_ok=True)
                shutil.copy(pp, lp)
                print(f"  ← pulled {label}")
            elif mode in ("merge", "pull") and os.path.getmtime(pp) > os.path.getmtime(lp):
                shutil.copy(lp, lp + ".pre-sync")
                shutil.copy(pp, lp)
                print(f"  ⇄ {label}: peer newer, local backed up")
            elif mode in ("merge", "push") and os.path.getmtime(lp) > os.path.getmtime(pp):
                shutil.copy(pp, pp + ".pre-sync")
                push_tar(cfg, ROOT, [os.path.join(rel, f)])
                print(f"  ⇄ {label}: local newer, pushed")
            else:
                # same age but different content — a real conflict
                print(f"  · {label}: same age, different content — keeping local")
                if mode == "push":
                    shutil.copy(pp, pp + ".pre-sync")
                    push_tar(cfg, ROOT, [os.path.join(rel, f)])
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "merge"
    if mode not in ("merge", "pull", "push"):
        sys.exit("usage: sync.py [merge|pull|push]")
    cfg = load_cfg()
    print(f"🐦‍⬛ R8s sync ({mode}) → {cfg['peer']}:{cfg['port']} {cfg['peer_home']}")
    sync_memory_merge(cfg, mode)
    for rel in MERGE_FILES:
        sync_plain_merge(cfg, rel, mode)
    sync_plain_merge(cfg, CON_DIR, mode)
    print("✅ sync complete")


if __name__ == "__main__":
    main()
