#!/bin/bash
echo "=================================="
echo "  AOS MISSION CONTROL ACCESS"
echo "=================================="
echo ""
echo "Status:"
systemctl is-active aos-mission-control && echo "✅ Service Running" || echo "❌ Service Stopped"
echo ""
echo "Local Access:"
echo "  http://localhost:8080"
echo ""
echo "Network Access:"
ip addr show | grep "inet " | head -3 | awk '{print "  http://" $2 ":8080"}' | sed 's|/24||' | sed 's|/20||'
echo ""
echo "To view from this machine:"
echo "  firefox http://localhost:8080"
echo "  OR"
echo "  google-chrome http://localhost:8080"
echo ""
echo "Service Logs:"
echo "  journalctl -u aos-mission-control -f"
