#!/usr/bin/env python3
"""
Morty's Brain Waste Report Generator v2.0
Queries Miles' brain via HTTP API and generates formatted waste reports.

Usage:
    python3 morty_waste_report.py [--output-dir ~/mortimer/brain-waste]
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import urlopen, URLError
from urllib.error import HTTPError

# Configuration
MILES_HOST = os.environ.get("MILES_HOST", "psdepot.com")
MILES_PORT = int(os.environ.get("MILES_PORT", "8080"))
DEFAULT_REPORT_DIR = Path.home() / "mortimer" / "brain-waste"


def fetch_api(endpoint: str, timeout: int = 10) -> dict:
    """Fetch JSON data from Miles' HTTP API."""
    url = f"http://{MILES_HOST}:{MILES_PORT}{endpoint}"
    try:
        with urlopen(url, timeout=timeout) as response:
            return json.loads(response.read().decode('utf-8'))
    except (URLError, HTTPError, TimeoutError) as e:
        return {"error": str(e), "url": url}


def format_report(brain_data: dict, timestamp: str) -> str:
    """Generate a formatted waste report."""
    lines = [
        "╔══════════════════════════════════════════════════════════════════════════════╗",
        "║                    MILES' BRAIN WASTE REPORT                                 ║",
        "╚══════════════════════════════════════════════════════════════════════════════╝",
        "",
        f"Generated: {timestamp}",
        f"Source: Miles_Brain_v4.5 (via HTTP API)",
        f"Host: {MILES_HOST}:{MILES_PORT}",
        "",
    ]
    
    # Brain status section
    if "error" in brain_data:
        lines.extend([
            "❌ BRAIN STATUS: CONNECTION FAILED",
            f"   Error: {brain_data['error']}",
            "",
        ])
    else:
        brain = brain_data.get("brain", {})
        lines.extend([
            "✅ BRAIN STATUS: CONNECTED",
            "",
            "┌─ Brain Metrics ──────────────────────────────────────────────────────────────┐",
            f"│  Version:        {brain.get('version', 'N/A')}",
            f"│  Current Tick:   {brain.get('tick', 'N/A')}",
            f"│  Phase:          {brain.get('phase', 'N/A')}",
            f"│  Signal Quality: {brain.get('signal_quality_20avg', 'N/A')}",
            f"│  Components:     {brain.get('components_active', 'N/A')}/15 active",
            "└──────────────────────────────────────────────────────────────────────────────┘",
            "",
        ])
        
        # Kidney data if available
        kidneys = brain.get("kidneys", {})
        if kidneys:
            lines.extend([
                "✅ KIDNEY STATUS: CONNECTED",
                "",
                "┌─ Kidney Metrics ─────────────────────────────────────────────────────────────┐",
                f"│  State:           {kidneys.get('state', 'N/A')}",
                f"│  Total Processed:  {kidneys.get('total_processed', 'N/A')}",
                f"│  Excreted:         {kidneys.get('excreted', 'N/A')}",
                f"│  Bladder Level:    {kidneys.get('bladder_level', 'N/A')}/500",
                f"│  Noise Estimate:   {kidneys.get('noise_estimate', 'N/A')}",
                f"│  Unique Patterns:  {kidneys.get('unique_patterns_seen', 'N/A')}",
                "└──────────────────────────────────────────────────────────────────────────────┘",
                "",
            ])
    
    lines.extend([
        "═══════════════════════════════════════════════════════════════════════════════",
        "",
        "This is an automated waste report from Miles' brain.",
        "Generated by Morty's waste report system (v2.0 - HTTP API)",
        "",
        "═══════════════════════════════════════════════════════════════════════════════",
        "",
    ])
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate waste reports from Miles' brain"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_REPORT_DIR,
        help="Directory to save waste reports"
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Test connection without saving report"
    )
    args = parser.parse_args()
    
    # Ensure report directory exists
    args.output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate timestamps
    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S UTC")
    datestamp = now.strftime("%Y%m%d-%H%M%S")
    
    print("=== Morty's Waste Report Generator ===")
    print(f"Querying Miles' brain at {MILES_HOST}:{MILES_PORT}...")
    print()
    
    # Fetch brain data
    print("Fetching brain status... ", end="", flush=True)
    brain_data = fetch_api("/api/status")
    if "error" not in brain_data:
        print("✅ OK")
    else:
        print(f"❌ FAILED: {brain_data['error']}")
    
    print()
    
    # Generate report
    report = format_report(brain_data, timestamp)
    
    if args.test:
        print("=== TEST MODE - Report would be saved to ===")
        print(f"{args.output_dir}/brain-waste-{datestamp}.txt")
        print()
        print(report)
        return 0
    
    # Save report
    report_file = args.output_dir / f"brain-waste-{datestamp}.txt"
    report_file.write_text(report)
    
    # Display report
    print("=== Report Generated ===")
    print(f"File: {report_file}")
    print()
    print(report)
    print(f"Report saved to: {report_file}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
