PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE psd_customers (id INTEGER PRIMARY KEY, name TEXT, status TEXT DEFAULT 'active', category TEXT, last_contact TEXT, system_type TEXT, city TEXT);
INSERT INTO psd_customers VALUES(1,'Sample Customer','active','Test',NULL,'TestPOS','Los Angeles');
INSERT INTO psd_customers VALUES(2,'20 Coffee Shop 1','active','coffee shop',NULL,'Unknown','Long Beach');
INSERT INTO psd_customers VALUES(3,'20 Restaurant 2','active','restaurant',NULL,'Unknown','Santa Ana');
INSERT INTO psd_customers VALUES(4,'20 Bistro 3','active','bistro',NULL,'Unknown','San Jose');
INSERT INTO psd_customers VALUES(5,'20 Bistro 4','active','bistro',NULL,'Unknown','Sacramento');
INSERT INTO psd_customers VALUES(6,'20 Taqueria 5','active','taqueria',NULL,'Unknown','Oakland');
INSERT INTO psd_customers VALUES(7,'20 Restaurant 6','active','restaurant',NULL,'Unknown','San Francisco');
INSERT INTO psd_customers VALUES(8,'20 Taqueria 7','active','taqueria',NULL,'Unknown','Anaheim');
INSERT INTO psd_customers VALUES(9,'20 Diner 8','active','diner',NULL,'Unknown','San Jose');
INSERT INTO psd_customers VALUES(10,'20 Coffee Shop 9','active','coffee shop',NULL,'Unknown','Los Angeles');
INSERT INTO psd_customers VALUES(11,'20 Restaurant 10','active','restaurant',NULL,'Unknown','San Jose');
INSERT INTO psd_customers VALUES(12,'20 Cafe 11','active','cafe',NULL,'Unknown','San Diego');
INSERT INTO psd_customers VALUES(13,'20 Coffee Shop 12','active','coffee shop',NULL,'Unknown','San Diego');
INSERT INTO psd_customers VALUES(14,'20 Coffee Shop 13','active','coffee shop',NULL,'Unknown','San Jose');
INSERT INTO psd_customers VALUES(15,'20 Bistro 14','active','bistro',NULL,'Unknown','San Francisco');
INSERT INTO psd_customers VALUES(16,'20 Coffee Shop 15','active','coffee shop',NULL,'Unknown','San Diego');
INSERT INTO psd_customers VALUES(17,'20 Bistro 16','active','bistro',NULL,'Unknown','Oakland');
INSERT INTO psd_customers VALUES(18,'20 Diner 17','active','diner',NULL,'Unknown','Oakland');
INSERT INTO psd_customers VALUES(19,'20 Restaurant 18','active','restaurant',NULL,'Unknown','San Jose');
INSERT INTO psd_customers VALUES(20,'20 Restaurant 19','active','restaurant',NULL,'Unknown','Los Angeles');
INSERT INTO psd_customers VALUES(21,'20 Cafe 20','active','cafe',NULL,'Unknown','Santa Ana');
INSERT INTO psd_customers VALUES(22,'Sofia & Family Deli','active','deli',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(23,'Pizza by Robert','active','pizza',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(24,'Pedro & Family Chinese','active','chinese',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(25,'Elena & Family Deli','active','deli',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(26,'Elena & Family Thai','active','thai',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(27,'Carlos Mexican','active','mexican',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(28,'Emma & Family Italian','active','italian',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(29,'Patricia & Family Diner','active','diner',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(30,'David Italian','active','italian',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(31,'Francisco & Family Pizza','active','pizza',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(32,'The Linda Restaurant','active','restaurant',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(33,'Lisa''s Breakfast','active','breakfast',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(34,'The Isabella Cafe','active','cafe',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(35,'Tony & Family Seafood','active','seafood',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(36,'The John Italian','active','italian',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(37,'Burger House','active','burger',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(38,'Tony Deli','active','deli',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(39,'Restaurant House','active','restaurant',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(40,'Taqueria by David','active','taqueria',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(41,'Seafood House','active','seafood',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(42,'Antonio Mexican','active','mexican',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(43,'Bbq by Jennifer','active','bbq',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(44,'Sushi by Juan','active','sushi',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(45,'Bbq by Carlos','active','bbq',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(46,'Robert Thai','active','thai',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(47,'Roberto''s Taqueria','active','taqueria',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(48,'Juan Steakhouse','active','steakhouse',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(49,'Luis''s Pizza','active','pizza',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(50,'Guadalupe''s Burger','active','burger',NULL,'Unknown','Dallas');
INSERT INTO psd_customers VALUES(51,'Jose & Family Sandwich','active','sandwich',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(52,'Elena & Family Cafe','active','cafe',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(53,'The Tony Thai','active','thai',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(54,'Sushi House','active','sushi',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(55,'Elena Deli','active','deli',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(56,'Mike & Family Restaurant','active','restaurant',NULL,'Unknown','Dallas');
INSERT INTO psd_customers VALUES(57,'Emma''s Burger','active','burger',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(58,'Mike''s Bakery','active','bakery',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(59,'Luis''s Place','active','italian',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(60,'Seafood House','active','seafood',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(61,'Food Truck House','active','food truck',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(62,'Elena & Family Breakfast','active','breakfast',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(63,'The Jose Thai','active','thai',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(64,'Sofia Bakery','active','bakery',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(65,'Guadalupe''s Place','active','food truck',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(66,'Antonio''s Place','active','bakery',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(67,'Deli by Linda','active','deli',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(68,'Elena''s Place','active','bakery',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(69,'Guadalupe & Family Thai','active','thai',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(70,'The Isabella Thai','active','thai',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(71,'Carlos''s Place','active','bbq',NULL,'Unknown','Dallas');
INSERT INTO psd_customers VALUES(72,'Carmen & Family Mexican','active','mexican',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(73,'Antonio''s Seafood','active','seafood',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(74,'Carlos''s Taqueria','active','taqueria',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(75,'The Carlos Bbq','active','bbq',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(76,'Pedro''s Seafood','active','seafood',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(77,'Hector Restaurant','active','restaurant',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(78,'Tony''s Sandwich','active','sandwich',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(79,'Michael''s Pizza','active','pizza',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(80,'Thai House','active','thai',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(81,'William''s Mexican','active','mexican',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(82,'Jose''s Chinese','active','chinese',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(83,'Tony & Family Pizza','active','pizza',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(84,'Mexican House','active','mexican',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(85,'Isabella''s Place','active','pizza',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(86,'The Luis Bakery','active','bakery',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(87,'Isabella & Family Sandwich','active','sandwich',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(88,'Jose''s Diner','active','diner',NULL,'Unknown','Dallas');
INSERT INTO psd_customers VALUES(89,'Sofia''s Bbq','active','bbq',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(90,'Thai by Lisa','active','thai',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(91,'David & Family Breakfast','active','breakfast',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(92,'Taqueria by Francisco','active','taqueria',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(93,'Isabella''s Thai','active','thai',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(94,'Carmen''s Sandwich','active','sandwich',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(95,'Linda''s Bbq','active','bbq',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(96,'The Jose Food Truck','active','food truck',NULL,'Unknown','Dallas');
INSERT INTO psd_customers VALUES(97,'The Rosa Diner','active','diner',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(98,'Burger by Michael','active','burger',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(99,'Linda''s Burger','active','burger',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(100,'Mexican House','active','mexican',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(101,'Thai House','active','thai',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(102,'Cafe by Jennifer','active','cafe',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(103,'Deli by Luis','active','deli',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(104,'William''s Pizza','active','pizza',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(105,'The Emma Restaurant','active','restaurant',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(106,'Emma''s Sandwich','active','sandwich',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(107,'Michael & Family Bbq','active','bbq',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(108,'Sandwich House','active','sandwich',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(109,'Luis''s Place','active','cafe',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(110,'Seafood by Pedro','active','seafood',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(111,'Tony & Family Steakhouse','active','steakhouse',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(112,'Breakfast by Emma','active','breakfast',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(113,'Maria & Family Food Truck','active','food truck',NULL,'Unknown','Dallas');
INSERT INTO psd_customers VALUES(114,'Guadalupe Deli','active','deli',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(115,'Tony Restaurant','active','restaurant',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(116,'Roberto & Family Seafood','active','seafood',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(117,'Isabella''s Chinese','active','chinese',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(118,'Carlos''s Thai','active','thai',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(119,'The Maria Breakfast','active','breakfast',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(120,'Guadalupe''s Place','active','pizza',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(121,'Mike & Family Vietnamese','active','vietnamese',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(122,'Robert''s Place','active','italian',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(123,'Francisco Sandwich','active','sandwich',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(124,'The Michael Deli','active','deli',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(125,'The Jose Sushi','active','sushi',NULL,'Unknown','Dallas');
INSERT INTO psd_customers VALUES(126,'Chinese by Emma','active','chinese',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(127,'Jennifer''s Place','active','diner',NULL,'Unknown','Dallas');
INSERT INTO psd_customers VALUES(128,'Antonio''s Vietnamese','active','vietnamese',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(129,'Sofia''s Seafood','active','seafood',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(130,'Sofia & Family Deli','active','deli',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(131,'Cafe House','active','cafe',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(132,'Patricia''s Place','active','restaurant',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(133,'Deli by Hector','active','deli',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(134,'Tony Thai','active','thai',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(135,'Cafe House','active','cafe',NULL,'Unknown','San Antonio');
INSERT INTO psd_customers VALUES(136,'Guadalupe & Family Bbq','active','bbq',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(137,'Sarah''s Place','active','sandwich',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(138,'Thai by David','active','thai',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(139,'Miguel & Family Italian','active','italian',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(140,'Isabella & Family Bbq','active','bbq',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(141,'Sandwich House','active','sandwich',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(142,'Francisco & Family Restaurant','active','restaurant',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(143,'William''s Taqueria','active','taqueria',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(144,'Roberto & Family Food Truck','active','food truck',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(145,'Pizza House','active','pizza',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(146,'The Rosa Bbq','active','bbq',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(147,'Robert''s Place','active','restaurant',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(148,'Michael''s Steakhouse','active','steakhouse',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(149,'Jose''s Deli','active','deli',NULL,'Unknown','Plano');
INSERT INTO psd_customers VALUES(150,'Burger House','active','burger',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(151,'Luis''s Place','active','chinese',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(152,'The Roberto Italian','active','italian',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(153,'David''s Mexican','active','mexican',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(154,'Linda''s Place','active','thai',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(155,'Emma & Family Burger','active','burger',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(156,'Tony''s Thai','active','thai',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(157,'Patricia''s Place','active','sandwich',NULL,'Unknown','Dallas');
INSERT INTO psd_customers VALUES(158,'Roberto''s Italian','active','italian',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(159,'Miguel''s Place','active','burger',NULL,'Unknown','Austin');
INSERT INTO psd_customers VALUES(160,'Jennifer & Family Vietnamese','active','vietnamese',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(161,'Robert''s Place','active','pizza',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(162,'The Antonio Mexican','active','mexican',NULL,'Unknown','Lubbock');
INSERT INTO psd_customers VALUES(163,'William''s Place','active','bakery',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(164,'Tony''s Diner','active','diner',NULL,'Unknown','Houston');
INSERT INTO psd_customers VALUES(165,'Steakhouse by Antonio','active','steakhouse',NULL,'Unknown','Fort Worth');
INSERT INTO psd_customers VALUES(166,'Roberto Chinese','active','chinese',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(167,'Chinese by Maria','active','chinese',NULL,'Unknown','Corpus Christi');
INSERT INTO psd_customers VALUES(168,'Lisa''s Place','active','deli',NULL,'Unknown','Arlington');
INSERT INTO psd_customers VALUES(169,'Luis''s Cafe','active','cafe',NULL,'Unknown','El Paso');
INSERT INTO psd_customers VALUES(170,'Portland Bakery #1','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(171,'Portland Catering #2','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(172,'Portland Food Truck #3','active','winery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(173,'Portland Bakery #4','active','catering',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(174,'Portland Catering #5','active','food truck',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(175,'Portland Brewery #6','active','catering',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(176,'Portland Cafe #7','active','brewery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(177,'Portland Food Truck #8','active','cafe',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(178,'Portland Distillery #9','active','restaurant',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(179,'Portland Cafe #10','active','brewery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(180,'Portland Winery #11','active','food truck',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(181,'Portland Food Truck #12','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(182,'Portland Distillery #13','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(183,'Portland Distillery #14','active','catering',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(184,'Portland Cafe #15','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(185,'Portland Restaurant #16','active','restaurant',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(186,'Portland Bakery #17','active','catering',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(187,'Portland Bakery #18','active','food truck',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(188,'Portland Catering #19','active','restaurant',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(189,'Portland Cafe #20','active','restaurant',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(190,'Portland Restaurant #21','active','bakery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(191,'Portland Catering #22','active','bakery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(192,'Portland Bakery #23','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(193,'Portland Brewery #24','active','winery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(194,'Portland Bakery #25','active','restaurant',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(195,'Portland Distillery #26','active','bakery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(196,'Portland Cafe #27','active','cafe',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(197,'Portland Cafe #28','active','food truck',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(198,'Portland Food Truck #29','active','cafe',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(199,'Portland Cafe #30','active','food truck',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(200,'Portland Restaurant #31','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(201,'Portland Cafe #32','active','restaurant',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(202,'Portland Catering #33','active','catering',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(203,'Portland Catering #34','active','bakery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(204,'Portland Bakery #35','active','winery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(205,'Portland Restaurant #36','active','restaurant',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(206,'Portland Restaurant #37','active','food truck',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(207,'Portland Winery #38','active','cafe',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(208,'Portland Catering #39','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(209,'Portland Winery #40','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(210,'Portland Distillery #41','active','bakery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(211,'Portland Winery #42','active','distillery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(212,'Portland Cafe #43','active','catering',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(213,'Portland Restaurant #44','active','food truck',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(214,'Portland Catering #45','active','food truck',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(215,'Portland Food Truck #46','active','brewery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(216,'Portland Food Truck #47','active','catering',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(217,'Portland Restaurant #48','active','bakery',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(218,'Portland Bakery #49','active','catering',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(219,'Portland Restaurant #50','active','restaurant',NULL,'Unknown','Portland');
INSERT INTO psd_customers VALUES(220,'Salem Cafe #1','active','catering',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(221,'Salem Restaurant #2','active','restaurant',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(222,'Salem Catering #3','active','restaurant',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(223,'Salem Food Truck #4','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(224,'Salem Winery #5','active','bakery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(225,'Salem Food Truck #6','active','bakery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(226,'Salem Food Truck #7','active','bakery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(227,'Salem Catering #8','active','catering',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(228,'Salem Catering #9','active','brewery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(229,'Salem Bakery #10','active','bakery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(230,'Salem Cafe #11','active','cafe',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(231,'Salem Food Truck #12','active','distillery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(232,'Salem Catering #13','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(233,'Salem Bakery #14','active','catering',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(234,'Salem Restaurant #15','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(235,'Salem Cafe #16','active','restaurant',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(236,'Salem Cafe #17','active','catering',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(237,'Salem Bakery #18','active','distillery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(238,'Salem Winery #19','active','food truck',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(239,'Salem Restaurant #20','active','brewery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(240,'Salem Distillery #21','active','bakery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(241,'Salem Restaurant #22','active','food truck',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(242,'Salem Distillery #23','active','cafe',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(243,'Salem Food Truck #24','active','cafe',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(244,'Salem Catering #25','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(245,'Salem Distillery #26','active','catering',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(246,'Salem Cafe #27','active','brewery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(247,'Salem Restaurant #28','active','catering',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(248,'Salem Food Truck #29','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(249,'Salem Cafe #30','active','brewery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(250,'Salem Winery #31','active','restaurant',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(251,'Salem Distillery #32','active','food truck',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(252,'Salem Food Truck #33','active','cafe',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(253,'Salem Distillery #34','active','food truck',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(254,'Salem Distillery #35','active','brewery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(255,'Salem Restaurant #36','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(256,'Salem Food Truck #37','active','cafe',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(257,'Salem Winery #38','active','bakery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(258,'Salem Food Truck #39','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(259,'Salem Distillery #40','active','catering',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(260,'Salem Food Truck #41','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(261,'Salem Winery #42','active','catering',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(262,'Salem Restaurant #43','active','brewery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(263,'Salem Brewery #44','active','cafe',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(264,'Salem Cafe #45','active','bakery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(265,'Salem Bakery #46','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(266,'Salem Bakery #47','active','winery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(267,'Salem Bakery #48','active','food truck',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(268,'Salem Catering #49','active','distillery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(269,'Salem Food Truck #50','active','distillery',NULL,'Unknown','Salem');
INSERT INTO psd_customers VALUES(270,'Eugene Bakery #1','active','brewery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(271,'Eugene Bakery #2','active','restaurant',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(272,'Eugene Restaurant #3','active','winery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(273,'Eugene Bakery #4','active','restaurant',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(274,'Eugene Distillery #5','active','food truck',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(275,'Eugene Brewery #6','active','cafe',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(276,'Eugene Cafe #7','active','winery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(277,'Eugene Food Truck #8','active','catering',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(278,'Eugene Distillery #9','active','food truck',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(279,'Eugene Catering #10','active','distillery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(280,'Eugene Cafe #11','active','bakery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(281,'Eugene Bakery #12','active','bakery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(282,'Eugene Catering #13','active','restaurant',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(283,'Eugene Food Truck #14','active','distillery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(284,'Eugene Catering #15','active','distillery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(285,'Eugene Winery #16','active','cafe',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(286,'Eugene Bakery #17','active','cafe',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(287,'Eugene Brewery #18','active','winery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(288,'Eugene Distillery #19','active','cafe',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(289,'Eugene Cafe #20','active','food truck',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(290,'Eugene Cafe #21','active','cafe',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(291,'Eugene Brewery #22','active','distillery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(292,'Eugene Cafe #23','active','brewery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(293,'Eugene Brewery #24','active','distillery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(294,'Eugene Cafe #25','active','catering',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(295,'Eugene Restaurant #26','active','cafe',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(296,'Eugene Distillery #27','active','brewery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(297,'Eugene Food Truck #28','active','food truck',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(298,'Eugene Distillery #29','active','catering',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(299,'Eugene Bakery #30','active','food truck',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(300,'Eugene Brewery #31','active','winery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(301,'Eugene Cafe #32','active','cafe',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(302,'Eugene Winery #33','active','brewery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(303,'Eugene Catering #34','active','winery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(304,'Eugene Cafe #35','active','cafe',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(305,'Eugene Cafe #36','active','winery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(306,'Eugene Food Truck #37','active','restaurant',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(307,'Eugene Winery #38','active','bakery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(308,'Eugene Food Truck #39','active','food truck',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(309,'Eugene Cafe #40','active','restaurant',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(310,'Eugene Brewery #41','active','bakery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(311,'Eugene Restaurant #42','active','cafe',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(312,'Eugene Cafe #43','active','winery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(313,'Eugene Food Truck #44','active','restaurant',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(314,'Eugene Bakery #45','active','distillery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(315,'Eugene Catering #46','active','restaurant',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(316,'Eugene Cafe #47','active','distillery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(317,'Eugene Restaurant #48','active','restaurant',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(318,'Eugene Brewery #49','active','catering',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(319,'Eugene Distillery #50','active','distillery',NULL,'Unknown','Eugene');
INSERT INTO psd_customers VALUES(320,'Gresham Restaurant #1','active','restaurant',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(321,'Gresham Food Truck #2','active','bakery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(322,'Gresham Catering #3','active','catering',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(323,'Gresham Cafe #4','active','catering',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(324,'Gresham Bakery #5','active','cafe',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(325,'Gresham Distillery #6','active','cafe',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(326,'Gresham Distillery #7','active','restaurant',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(327,'Gresham Bakery #8','active','cafe',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(328,'Gresham Winery #9','active','distillery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(329,'Gresham Brewery #10','active','restaurant',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(330,'Gresham Cafe #11','active','food truck',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(331,'Gresham Restaurant #12','active','brewery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(332,'Gresham Catering #13','active','cafe',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(333,'Gresham Brewery #14','active','catering',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(334,'Gresham Distillery #15','active','cafe',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(335,'Gresham Distillery #16','active','bakery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(336,'Gresham Winery #17','active','catering',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(337,'Gresham Winery #18','active','bakery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(338,'Gresham Bakery #19','active','cafe',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(339,'Gresham Cafe #20','active','food truck',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(340,'Gresham Food Truck #21','active','bakery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(341,'Gresham Food Truck #22','active','catering',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(342,'Gresham Catering #23','active','brewery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(343,'Gresham Catering #24','active','brewery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(344,'Gresham Restaurant #25','active','bakery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(345,'Gresham Food Truck #26','active','distillery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(346,'Gresham Food Truck #27','active','brewery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(347,'Gresham Bakery #28','active','restaurant',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(348,'Gresham Distillery #29','active','catering',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(349,'Gresham Distillery #30','active','distillery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(350,'Gresham Distillery #31','active','brewery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(351,'Gresham Food Truck #32','active','winery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(352,'Gresham Restaurant #33','active','winery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(353,'Gresham Catering #34','active','distillery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(354,'Gresham Restaurant #35','active','restaurant',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(355,'Gresham Winery #36','active','winery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(356,'Gresham Brewery #37','active','brewery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(357,'Gresham Restaurant #38','active','cafe',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(358,'Gresham Brewery #39','active','distillery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(359,'Gresham Catering #40','active','food truck',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(360,'Gresham Catering #41','active','restaurant',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(361,'Gresham Food Truck #42','active','restaurant',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(362,'Gresham Brewery #43','active','catering',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(363,'Gresham Bakery #44','active','catering',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(364,'Gresham Catering #45','active','food truck',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(365,'Gresham Winery #46','active','food truck',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(366,'Gresham Catering #47','active','restaurant',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(367,'Gresham Restaurant #48','active','cafe',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(368,'Gresham Brewery #49','active','brewery',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(369,'Gresham Catering #50','active','cafe',NULL,'Unknown','Gresham');
INSERT INTO psd_customers VALUES(370,'Bend Food Truck #1','active','distillery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(371,'Bend Cafe #2','active','winery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(372,'Bend Winery #3','active','winery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(373,'Bend Catering #4','active','distillery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(374,'Bend Winery #5','active','bakery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(375,'Bend Distillery #6','active','brewery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(376,'Bend Catering #7','active','distillery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(377,'Bend Catering #8','active','distillery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(378,'Bend Winery #9','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(379,'Bend Food Truck #10','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(380,'Bend Bakery #11','active','catering',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(381,'Bend Cafe #12','active','catering',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(382,'Bend Restaurant #13','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(383,'Bend Catering #14','active','restaurant',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(384,'Bend Distillery #15','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(385,'Bend Catering #16','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(386,'Bend Bakery #17','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(387,'Bend Cafe #18','active','cafe',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(388,'Bend Winery #19','active','catering',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(389,'Bend Bakery #20','active','distillery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(390,'Bend Distillery #21','active','cafe',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(391,'Bend Cafe #22','active','winery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(392,'Bend Restaurant #23','active','catering',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(393,'Bend Bakery #24','active','restaurant',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(394,'Bend Bakery #25','active','catering',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(395,'Bend Catering #26','active','winery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(396,'Bend Winery #27','active','restaurant',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(397,'Bend Catering #28','active','bakery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(398,'Bend Food Truck #29','active','restaurant',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(399,'Bend Bakery #30','active','cafe',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(400,'Bend Food Truck #31','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(401,'Bend Restaurant #32','active','catering',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(402,'Bend Restaurant #33','active','restaurant',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(403,'Bend Food Truck #34','active','distillery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(404,'Bend Catering #35','active','brewery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(405,'Bend Restaurant #36','active','bakery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(406,'Bend Bakery #37','active','restaurant',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(407,'Bend Winery #38','active','catering',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(408,'Bend Brewery #39','active','cafe',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(409,'Bend Brewery #40','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(410,'Bend Restaurant #41','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(411,'Bend Catering #42','active','bakery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(412,'Bend Cafe #43','active','brewery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(413,'Bend Winery #44','active','catering',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(414,'Bend Brewery #45','active','restaurant',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(415,'Bend Bakery #46','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(416,'Bend Brewery #47','active','distillery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(417,'Bend Winery #48','active','bakery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(418,'Bend Cafe #49','active','food truck',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(419,'Bend Restaurant #50','active','brewery',NULL,'Unknown','Bend');
INSERT INTO psd_customers VALUES(420,'Seattle Food Truck #1','active','cafe',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(421,'Seattle Restaurant #2','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(422,'Seattle Winery #3','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(423,'Seattle Coffee Shop #4','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(424,'Seattle Restaurant #5','active','bakery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(425,'Seattle Cafe #6','active','bakery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(426,'Seattle Seafood #7','active','coffee shop',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(427,'Seattle Coffee Shop #8','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(428,'Seattle Seafood #9','active','food truck',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(429,'Seattle Bakery #10','active','cafe',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(430,'Seattle Cafe #11','active','seafood',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(431,'Seattle Food Truck #12','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(432,'Seattle Coffee Shop #13','active','seafood',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(433,'Seattle Food Truck #14','active','restaurant',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(434,'Seattle Food Truck #15','active','bakery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(435,'Seattle Restaurant #16','active','food truck',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(436,'Seattle Restaurant #17','active','food truck',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(437,'Seattle Coffee Shop #18','active','coffee shop',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(438,'Seattle Seafood #19','active','restaurant',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(439,'Seattle Coffee Shop #20','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(440,'Seattle Brewery #21','active','restaurant',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(441,'Seattle Food Truck #22','active','coffee shop',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(442,'Seattle Cafe #23','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(443,'Seattle Restaurant #24','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(444,'Seattle Brewery #25','active','bakery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(445,'Seattle Seafood #26','active','seafood',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(446,'Seattle Restaurant #27','active','seafood',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(447,'Seattle Coffee Shop #28','active','bakery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(448,'Seattle Bakery #29','active','seafood',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(449,'Seattle Brewery #30','active','food truck',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(450,'Seattle Winery #31','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(451,'Seattle Seafood #32','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(452,'Seattle Cafe #33','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(453,'Seattle Food Truck #34','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(454,'Seattle Seafood #35','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(455,'Seattle Cafe #36','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(456,'Seattle Restaurant #37','active','seafood',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(457,'Seattle Bakery #38','active','restaurant',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(458,'Seattle Seafood #39','active','food truck',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(459,'Seattle Restaurant #40','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(460,'Seattle Bakery #41','active','restaurant',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(461,'Seattle Bakery #42','active','coffee shop',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(462,'Seattle Food Truck #43','active','seafood',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(463,'Seattle Seafood #44','active','restaurant',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(464,'Seattle Bakery #45','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(465,'Seattle Coffee Shop #46','active','bakery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(466,'Seattle Cafe #47','active','restaurant',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(467,'Seattle Cafe #48','active','restaurant',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(468,'Seattle Brewery #49','active','food truck',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(469,'Seattle Brewery #50','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(470,'Seattle Restaurant #51','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(471,'Seattle Bakery #52','active','seafood',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(472,'Seattle Winery #53','active','food truck',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(473,'Seattle Coffee Shop #54','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(474,'Seattle Restaurant #55','active','cafe',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(475,'Seattle Coffee Shop #56','active','coffee shop',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(476,'Seattle Winery #57','active','winery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(477,'Seattle Winery #58','active','seafood',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(478,'Seattle Brewery #59','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(479,'Seattle Winery #60','active','brewery',NULL,'Unknown','Seattle');
INSERT INTO psd_customers VALUES(480,'Spokane Brewery #1','active','coffee shop',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(481,'Spokane Bakery #2','active','food truck',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(482,'Spokane Coffee Shop #3','active','coffee shop',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(483,'Spokane Food Truck #4','active','winery',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(484,'Spokane Brewery #5','active','bakery',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(485,'Spokane Winery #6','active','bakery',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(486,'Spokane Restaurant #7','active','food truck',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(487,'Spokane Seafood #8','active','restaurant',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(488,'Spokane Cafe #9','active','bakery',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(489,'Spokane Coffee Shop #10','active','bakery',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(490,'Spokane Cafe #11','active','seafood',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(491,'Spokane Cafe #12','active','food truck',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(492,'Spokane Brewery #13','active','seafood',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(493,'Spokane Restaurant #14','active','brewery',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(494,'Spokane Brewery #15','active','restaurant',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(495,'Spokane Bakery #16','active','seafood',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(496,'Spokane Coffee Shop #17','active','restaurant',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(497,'Spokane Seafood #18','active','food truck',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(498,'Spokane Coffee Shop #19','active','brewery',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(499,'Spokane Cafe #20','active','restaurant',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(500,'Spokane Food Truck #21','active','brewery',NULL,'Unknown','Spokane');
INSERT INTO psd_customers VALUES(501,'Spokane Winery #22','active','coffee shop',NULL,'Unknown','Spokane');
COMMIT;
