# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aos_pm01_pb2 as aos__pm01__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aos_pm01_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AOSPM01BridgeStub:
    """Bidirectional streaming service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCommand = channel.unary_unary(
                '/aospm01.AOSPM01Bridge/SendCommand',
                request_serializer=aos__pm01__pb2.IntentCommand.SerializeToString,
                response_deserializer=aos__pm01__pb2.CommandAck.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/aospm01.AOSPM01Bridge/StreamState',
                request_serializer=aos__pm01__pb2.StateRequest.SerializeToString,
                response_deserializer=aos__pm01__pb2.RobotState.FromString,
                _registered_method=True)
        self.AgentLoop = channel.stream_stream(
                '/aospm01.AOSPM01Bridge/AgentLoop',
                request_serializer=aos__pm01__pb2.IntentCommand.SerializeToString,
                response_deserializer=aos__pm01__pb2.RLAction.FromString,
                _registered_method=True)


class AOSPM01BridgeServicer:
    """Bidirectional streaming service
    """

    def SendCommand(self, request, context):
        """Send high-level intent commands to robot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """Stream robot state back to brain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentLoop(self, request_iterator, context):
        """Bidirectional: intent in, actions out
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AOSPM01BridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=aos__pm01__pb2.IntentCommand.FromString,
                    response_serializer=aos__pm01__pb2.CommandAck.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=aos__pm01__pb2.StateRequest.FromString,
                    response_serializer=aos__pm01__pb2.RobotState.SerializeToString,
            ),
            'AgentLoop': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentLoop,
                    request_deserializer=aos__pm01__pb2.IntentCommand.FromString,
                    response_serializer=aos__pm01__pb2.RLAction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aospm01.AOSPM01Bridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aospm01.AOSPM01Bridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AOSPM01Bridge:
    """Bidirectional streaming service
    """

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aospm01.AOSPM01Bridge/SendCommand',
            aos__pm01__pb2.IntentCommand.SerializeToString,
            aos__pm01__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aospm01.AOSPM01Bridge/StreamState',
            aos__pm01__pb2.StateRequest.SerializeToString,
            aos__pm01__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentLoop(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aospm01.AOSPM01Bridge/AgentLoop',
            aos__pm01__pb2.IntentCommand.SerializeToString,
            aos__pm01__pb2.RLAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
