// Top-level build file for ReggieStarr RS-80
plugins {
    id 'com.android.application' version '8.2.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.20' apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext {
    compileSdk = 34
    minSdk = 23
    targetSdk = 34
}