#!/bin/bash
echo "=== Security Probe Status ==="
echo ""
echo "AIDE:"
aide --check 2>/dev/null | head -3 || echo "  Database initialized"
echo ""
echo "auditd:"
systemctl status auditd --no-pager 2>/dev/null | head -5 || echo "  Status unknown"
echo ""
echo "node_exporter:"
systemctl status node-exporter --no-pager 2>/dev/null | head -5 || echo "  Status unknown"
echo ""
echo "Custom probe (cron):"
crontab -l | grep security-probe || echo "  Not in cron"
echo ""
echo "Metrics endpoint: http://localhost:9100/metrics"
