#!/bin/bash
# DAILY QUEUE EMAIL REPORT TO CAPTAIN
# Job ID: 5bb713dd-5a57-4c6a-84fc-0c1d403c83eb
# Cron: Daily at 13:23 UTC
# Description: Run daily queue report and email to Captain

set -e

# Configuration
WORKSPACE="/root/.openclaw/workspace"
QUEUE_DIR="${WORKSPACE}/queue"
REPORT_DATE=$(date -u +"%Y-%m-%d")
REPORT_TIME=$(date -u +"%H:%M:%S")
REPORT_FILE="${QUEUE_DIR}/DAILY_STATUS_${REPORT_DATE}.md"
RECIPIENT="Antonio.hudnall@gmail.com"
JOB_NAME="AGI-DAILY-QUEUE-STATUS-THIS-BEAST"
RUN_ID="${JOB_NAME}-${REPORT_DATE}"

echo "═══════════════════════════════════════════════════════════"
echo "  🚀 ${JOB_NAME}"
echo "  ⏰ ${REPORT_DATE} ${REPORT_TIME} UTC"
echo "  📧 Emailing: ${RECIPIENT}"
echo "═══════════════════════════════════════════════════════════"

# Ensure queue directory exists
mkdir -p "${QUEUE_DIR}"

# Generate the daily report
echo ""
echo "📄 Generating report..."

if [ -f "${WORKSPACE}/scripts/daily_queue_email_report.sh" ]; then
    # Use the existing script to generate report
    bash "${WORKSPACE}/scripts/daily_queue_email_report.sh" 2>&1 || echo "Warning: Report generation script had issues"
else
    echo "⚠️  Report generation script not found at ${WORKSPACE}/scripts/daily_queue_email_report.sh"
fi

# Find the report file (could be today or yesterday's format)
LATEST_REPORT=$(ls -t ${QUEUE_DIR}/DAILY_STATUS_*.md 2>/dev/null | head -1)

if [ -z "${LATEST_REPORT}" ]; then
    echo "❌ No report file found in ${QUEUE_DIR}"
    exit 1
fi

echo "✓ Report file: ${LATEST_REPORT}"

# Check if mail command is available
if ! command -v mail &> /dev/null; then
    echo "⚠️  'mail' command not found. Installing..."
    apt-get update -qq && apt-get install -y -qq mailutils 2>/dev/null || echo "Could not install mailutils"
fi

# Check for email credentials in environment
if [ -n "$SMTP_USER" ] && [ -n "$SMTP_PASS" ]; then
    echo "🔐 Using environment SMTP credentials"
else
    echo "⚠️  SMTP credentials not set in environment"
    echo "   Set: SMTP_USER, SMTP_PASS, SMTP_HOST (optional), SMTP_PORT (optional)"
fi

# Build email subject
SUBJECT="🚀 ${JOB_NAME} - Daily Report ${REPORT_DATE}"

# Read report content
REPORT_CONTENT=$(cat "${LATEST_REPORT}" 2>/dev/null)

if [ -z "${REPORT_CONTENT}" ]; then
    echo "❌ Report file is empty"
    exit 1
fi

# Send email via mail command
echo ""
echo "📧 Sending email to Captain..."

# Create email with attachment
(
echo "Subject: ${SUBJECT}"
echo "To: ${RECIPIENT}"
echo "Content-Type: multipart/mixed; boundary=\"BOUNDARY12345\""
echo "MIME-Version: 1.0"
echo ""
echo "--BOUNDARY12345"
echo "Content-Type: text/plain; charset=UTF-8"
echo "Content-Transfer-Encoding: quoted-printable"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  DAILY QUEUE STATUS REPORT - ${REPORT_DATE}"
echo "  Generated: ${REPORT_TIME} UTC"
echo "  Job: ${JOB_NAME}"
echo "══════════════════════════════════════════════════════════════="
echo ""
echo "Hello Captain,"
echo ""
echo "Your daily queue status report is attached. Summary below:"
echo ""

# Extract key sections from report
grep -A 50 "## ⏳ ACTIVE QUEUE" "${LATEST_REPORT}" 2>/dev/null | head -20 || echo "Queue section not found"

echo ""
echo "--"
echo "Generated by Miles (Autonomous Operations Engine)"
echo "OpenClaw Gateway | AGI Company"
echo ""
echo "--BOUNDARY12345"
echo "Content-Type: text/markdown; charset=UTF-8; name=\"$(basename ${LATEST_REPORT})\""
echo "Content-Disposition: attachment; filename=\"$(basename ${LATEST_REPORT})\""
echo "Content-Transfer-Encoding: base64"
echo ""
base64 "${LATEST_REPORT}"
echo ""
echo "--BOUNDARY12345--"
) | sendmail -t 2>/dev/null || (
    # Fallback to simple mail command
    echo "Subject: ${SUBJECT}"
    echo "To: ${RECIPIENT}"
    echo ""
    echo "Daily Queue Report for ${REPORT_DATE}"
    echo ""
    echo "---"
    cat "${LATEST_REPORT}"
) | mail -s "${SUBJECT}" "${RECIPIENT}" 2>/dev/null

# Check if email was sent successfully
if [ $? -eq 0 ]; then
    echo "✅ Email sent successfully to ${RECIPIENT}"
    echo "   Subject: ${SUBJECT}"
    echo "   Attachment: $(basename ${LATEST_REPORT})"
    
    # Log success
    echo "[$(date -u +"%Y-%m-%d %H:%M:%S")] SUCCESS: ${JOB_NAME} - Email sent to ${RECIPIENT}" >> "${WORKSPACE}/cron/cron.log"
else
    echo "❌ Failed to send email"
    echo "[$(date -u +"%Y-%m-%d %H:%M:%S")] ERROR: ${JOB_NAME} - Email failed" >> "${WORKSPACE}/cron/cron.log"
    exit 1
fi

# Also commit to GitHub if token is available
if [ -n "$GITHUB_TOKEN" ]; then
    echo ""
    echo "📤 Committing to GitHub..."
    cd "${WORKSPACE}"
    git add "${LATEST_REPORT}" 2>/dev/null || true
    git commit -m "${JOB_NAME}: ${REPORT_DATE} - Daily status" 2>/dev/null || true
    git push origin master 2>/dev/null && echo "✅ GitHub updated" || echo "⚠️  GitHub push skipped"
fi

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  ✅ Job Complete: ${RUN_ID}"
echo "═══════════════════════════════════════════════════════════"
