#!/usr/bin/env python3
"""
Patricia Task Tracking Automation System
Authorizes automated daily task tracking, freshness checks, and escalations
Approved: 2026-06-30
"""

import os
import json
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
import subprocess

# Config
DB_PATH = "/root/.openclaw/workspace/data/depot_chaos/unified.db"
AGENT_SANDBOXES = "/root/.openclaw/workspace/agent_sandboxes"
LOG_FILE = "/var/log/aos/patricia_task_automation.log"
ALERT_DAYS = 7
CRITICAL_DAYS = 14
ESCALATION_DAYS = 30

def log(message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_line = f"[Patricia Automation] {timestamp}: {message}"
    print(log_line)
    Path(LOG_FILE).parent.mkdir(parents=True, exist_ok=True)
    with open(LOG_FILE, 'a') as f:
        f.write(log_line + "\n")

def check_task_freshness():
    """Check all agent tasks for staleness"""
    log("Starting task freshness check...")
    
    alerts = []
    warnings = []
    criticals = []
    
    for agent_dir in Path(AGENT_SANDBOXES).iterdir():
        if not agent_dir.is_dir():
            continue
            
        agent_name = agent_dir.name
        tasks_dir = agent_dir / "tasks"
        heartbeat_file = agent_dir / ".heartbeat_trigger"
        
        # Check heartbeat
        if heartbeat_file.exists():
            mtime = datetime.fromtimestamp(heartbeat_file.stat().st_mtime)
            age_days = (datetime.now() - mtime).days
            
            if age_days > CRITICAL_DAYS:
                criticals.append(f"{agent_name}: Heartbeat {age_days} days old")
            elif age_days > ALERT_DAYS:
                alerts.append(f"{agent_name}: Heartbeat {age_days} days old")
        else:
            warnings.append(f"{agent_name}: No heartbeat file")
        
        # Check tasks
        if tasks_dir.exists():
            for task_file in tasks_dir.glob("*.md"):
                mtime = datetime.fromtimestamp(task_file.stat().st_mtime)
                age_days = (datetime.now() - mtime).days
                task_name = task_file.stem
                
                if age_days > ESCALATION_DAYS:
                    criticals.append(f"{agent_name}/{task_name}: {age_days} DAYS - ESCALATE TO CAPTAIN")
                elif age_days > CRITICAL_DAYS:
                    criticals.append(f"{agent_name}/{task_name}: {age_days} days")
                elif age_days > ALERT_DAYS:
                    alerts.append(f"{agent_name}/{task_name}: {age_days} days")
    
    return {
        'alerts': alerts,
        'warnings': warnings,
        'criticals': criticals,
        'total_checked': len(list(Path(AGENT_SANDBOXES).iterdir()))
    }

def generate_daily_standup():
    """Auto-generate daily standup report"""
    today = datetime.now().strftime("%Y-%m-%d")
    report_path = f"/root/.openclaw/workspace/aocros/daily_standups/{today}_auto_standup.md"
    
    freshness = check_task_freshness()
    
    report = f"""# Auto-Generated Daily Standup — {today}
**Generated by Patricia Task Automation System**
**Time:** {datetime.now().strftime("%H:%M UTC")}

---

## Task Freshness Report

### 🔴 CRITICAL ({len(freshness['criticals'])} items)
"""
    
    for item in freshness['criticals']:
        report += f"- {item}\n"
    
    report += f"""
### 🟡 ALERTS ({len(freshness['alerts'])} items)
"""
    
    for item in freshness['alerts']:
        report += f"- {item}\n"
    
    report += f"""
### 🟢 WARNINGS ({len(freshness['warnings'])} items)
"""
    
    for item in freshness['warnings']:
        report += f"- {item}\n"
    
    report += f"""
---

## System Status (Auto-Check)

| Service | Status | Notes |
|---------|--------|-------|
| Brain v4 | {check_service('aos-brain-v4')} | Auto-checked |
| Mission Control | {check_service('aos-mission-control')} | Auto-checked |
| CA SOS Scraper | {check_service('continuous-scraper')} | Auto-checked |
| DepotChaos | {check_service('depotchaos')} | Auto-checked |

---

## Actions Required

1. **Review CRITICAL items** — Address within 24h
2. **Update stale PENDING_TASKS** — All agents with >{ALERT_DAYS} day items
3. **Verify escalations** — Captain review for >{ESCALATION_DAYS} day items

---

*This report was auto-generated by Patricia's Task Tracking Automation System.*
*Approved by Captain: 2026-06-30*
"""
    
    with open(report_path, 'w') as f:
        f.write(report)
    
    log(f"Generated standup report: {report_path}")
    return report_path

def check_service(service_name):
    """Quick service health check"""
    try:
        result = subprocess.run(
            ['systemctl', 'is-active', service_name],
            capture_output=True,
            text=True,
            timeout=5
        )
        return "✅ Active" if result.returncode == 0 else "⚠️ Inactive"
    except:
        return "❌ Check failed"

def send_escalation_alert(critical_items):
    """Send escalation email for critical items"""
    if not critical_items:
        return
    
    log(f"ESCALATION: {len(critical_items)} critical items require Captain attention")
    
    # Create escalation file
    escalation_path = f"/root/.openclaw/workspace/aocros/escalations/{datetime.now().strftime('%Y-%m-%d')}_CRITICAL.md"
    Path(escalation_path).parent.mkdir(parents=True, exist_ok=True)
    
    with open(escalation_path, 'w') as f:
        f.write(f"""# CRITICAL ESCALATION — {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Items Requiring Captain Intervention

""")
        for item in critical_items:
            f.write(f"- [ ] {item}\n")
    
    log(f"Escalation file created: {escalation_path}")

def main():
    """Main automation routine"""
    log("=" * 60)
    log("Patricia Task Tracking Automation — Starting")
    log("=" * 60)
    
    # Check task freshness
    freshness = check_task_freshness()
    log(f"Checked {freshness['total_checked']} agents")
    log(f"Found: {len(freshness['criticals'])} critical, {len(freshness['alerts'])} alerts, {len(freshness['warnings'])} warnings")
    
    # Generate daily standup
    report_path = generate_daily_standup()
    
    # Send escalations if any
    if freshness['criticals']:
        send_escalation_alert(freshness['criticals'])
    
    log("Automation complete")
    log(f"Standup report: {report_path}")

if __name__ == "__main__":
    main()
