#!/usr/bin/env python3
"""Email Santa Rosa restaurant lead summary to Captain + psdepot."""
import smtplib, re
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.utils import formataddr

# load creds
env = open("/root/.openclaw/workspace/.env").read()
user = re.search(r"HOSTINGER_SMTP_USER=(.+)", env).group(1).strip()
pw = re.search(r"HOSTINGER_SMTP_PASS=(.+)", env).group(1).strip()

LEADS = [
 ("Sweet T's Restaurant + Bar","(707) 595-3935","2097 Stagecoach Rd Ste 100","Restaurant / Bar","sweettssr@sweettssr.com","sweettssr.com"),
 ("Union Hotel Restaurant","(707) 538-6000","280 Mission Blvd","American / Pizza","","theunionhotel.com"),
 ("Carlos' Country Kitchen","(707) 569-9734","90 W College Ave","Home Cooking / American","",""),
 ("Ting Hau Restaurant","(707) 545-5204","717 4th St","Chinese","","tinghau.com"),
 ("Kirin Restaurant","(707) 525-1957","2700 Yulupa Ave Ste 3","Asian / Family Style","","kirinsantarosa.com"),
 ("Lita's Cafe","(707) 575-1628","1973 Mendocino Ave","American / Coffee","","litascafe.com"),
 ("John Ash & Co","(707) 527-7687","4330 Barnes Rd","American / Cocktail","","johnashandco.com"),
 ("Shogun Japanese Restaurant","(707) 575-5557","2350 Midway Dr","Japanese","",""),
 ("Zazu Restaurant & Farm","(707) 523-4814","3535 Guerneville Rd","Family Style / Catering","","zazurestaurant.com"),
 ("Taqueria El Rodeo","(707) 528-1964","3577 Industrial Dr","Mexican","","taqueriaelrodeo.com"),
 ("Monti's Rotisserie & Bar","(707) 568-4404","714 Village Ct","American / Chicken","",""),
 ("El Charro Mexican Restaurant","(707) 570-2387","1529 Farmers Ln","Mexican","","elcharromexican.com"),
 ("Bellys Left Coast and Tap Room","(707) 526-5787","523 4th St","American","",""),
 ("Cafe Citti","(707) 523-2690","2792 4th St","Coffee / Italian","",""),
 ("Crepevine","(707) 577-8822","740 Farmers Ln","American / Breakfast","","crepevine.com"),
 ("Johnny Garlics","(707) 571-1800","1460 Farmers Ln","American","","johnnygarlics.com"),
 ("Trattoria Cattaneo","(707) 542-9050","2700 Yulupa Ave Ste 10","Italian","juliecattaneo@mac.com","trattoriacattaneo.com"),
 ("Mel's Fish & Chips","(707) 578-1954","1016 Hopper Ave","Seafood","","melsfishandchips.com"),
 ("Ca'Bianca Ristorante Italiano","(707) 542-5800","835 2nd St","Italian","","cabianca.com"),
 ("Toyo Restaurant","(707) 527-8871","3082 Marlow Rd Ste B3","Japanese / Sushi","","toyosushi.com"),
 ("Fabianis Ristorante","(707) 595-1177","505 Mendocino Ave","Italian","",""),
 ("BJ's Restaurants","(707) 303-1980","334 Coddingtown Ctr","American / Pizza","","bjsrestaurants.com"),
 ("The BBQ Spot","(707) 585-2616","3448 Santa Rosa Ave","Barbecue","","thebbqspot.com"),
 ("Norm Kitchen","(707) 579-4007","478 Larkfield Ctr","Family Style","",""),
 ("The Terrace Grille","(707) 523-4745","2777 4th St","Family Style","hello@flamingoresort.com","flamingoresort.com"),
 ("Thai House","(707) 526-3939","525 4th St","Thai","thaihousesantarosa@gmail.com","thaihousesantarosa.com"),
 ("Ike's Place","(707) 293-9814","1780 Mendocino Ave","American / Sandwiches","","ikesloveandsandwiches.com"),
 ("Sea Thai Bistro","(707) 528-8333","2350 Midway Dr","Thai","info@seathaibistro.com","seathaibistro.com"),
 ("Chelino's Mexican Restaurant","(707) 571-7478","1079 4th St","Mexican","contactus@chelinos.net","chelinos.com"),
 ("Royal China Restaurant","(707) 545-2911","3080 Marlow Rd Ste A4","Chinese","",""),
]

# Build HTML table
rows = []
for name, phone, addr, cat, email, web in LEADS:
    email_cell = email if email else '<span style="color:#999">—</span>'
    web_cell = web if web else "—"
    rows.append(f"<tr><td>{name}</td><td>{phone}</td><td>{cat}</td><td>{email_cell}</td><td>{web_cell}</td></tr>")

email_found = sum(1 for l in LEADS if l[4])
html = f"""
<html><body style="font-family:Arial,sans-serif;font-size:14px;color:#222">
<h2>Santa Rosa Restaurant Leads — DepotChaos Import</h2>
<p>Scraped {len(LEADS)} restaurants from Yelp (Santa Rosa, CA). All {len(LEADS)} inserted into DepotChaos
(<code>leads</code>, source <code>Santa_Rosa_Yelp</code>, assigned to <code>datadepot_sales</code>, status <code>new</code>).</p>
<p><strong>Emails found: {email_found} of {len(LEADS)}</strong> — most small spots only publish a phone or contact form.</p>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-size:13px">
<tr style="background:#f0f0f0"><th align="left">Business</th><th align="left">Phone</th><th align="left">Category</th><th align="left">Email</th><th align="left">Website</th></tr>
{''.join(rows)}
</table>
<p style="color:#666;font-size:12px">Generated by Miles (AOS) — 2026-08-29. Beets is building a YellowPages city-scraper for Petaluma/Napa/Sebastopol/Healdsburg/Rohnert Park next.</p>
</body></html>
"""

msg = MIMEMultipart("alternative")
msg["Subject"] = "Santa Rosa Restaurant Leads — 30 imported to DepotChaos (6 emails)"
msg["From"] = formataddr(("Miles (PSD)", "miles@myl0nr0s.cloud"))
msg["To"] = "info@psdepot.com, Antonio.hudnall@gmail.com"
msg.attach(MIMEText(html, "html"))

recipients = ["info@psdepot.com", "Antonio.hudnall@gmail.com"]

with smtplib.SMTP("smtp.hostinger.com", 587, timeout=30) as s:
    s.starttls()
    s.login(user, pw)
    s.sendmail(user, recipients, msg.as_string())

print("Sent to", recipients)
