#!/bin/bash
# GitHub Webhook Manual Configuration Helper
# Miles Communication Pipe — Now Active

clear
echo ""
echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║              GITHUB WEBHOOK CONFIGURATION REQUIRED                       ║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "🌐 PUBLIC ENDPOINT: https://aocros-miles-webhook.loca.lt/webhook"
echo ""
echo "Since this server has IPv6 only, we need MANUAL webhook setup:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Go to GitHub Repository Settings:"
echo ""
echo "    https://github.com/hcindus/performance-supply-depot/settings/hooks"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "2️⃣  Click 'Add webhook'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3️⃣  Fill in the form:"
echo ""
echo "    Payload URL:"
echo "    https://aocros-miles-webhook.loca.lt/webhook"
echo ""
echo "    Content type:"
echo "    application/json"
echo ""
echo "    Secret:"
echo "    AOCROS-WEBHOOK-2025"
echo ""
echo "    SSL verification:"
echo "    Enable (default)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "4️⃣  Select events:"
echo ""
echo "    [✓] Just the push event"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "5️⃣  Click 'Add webhook'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ That's it! Miles commits will now trigger instant notifications (~2s)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Current Status:"
echo ""
echo "    Local Receiver:   ✅ Running on port 9001"
echo "    Tunnel:           ✅ Active (localtunnel)"
echo "    GitHub Webhook:   ⏳ Awaiting manual configuration"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔒 Security:"
echo ""
echo "    • HMAC-SHA256 signature verification active"
echo "    • Secret: AOCROS-WEBHOOK-2025"
echo "    • Logs: /var/log/openclaw/webhook/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Fallback:"
echo ""
echo "    If webhook fails, 30-second Git polling continues as backup"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
