# Project-wide Gradle configuration

# IDE
droid.nonTransitiveRClass=true
kotlin.code.style=official

# Performance
org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# Android
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.incremental=true
kapt.incremental.apt=true

# Compose
android.enableBuildCache=true
